server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_home?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.purpleglow.entity